# Header
menu:
  Home: /
  Category: /categories
  Archive: /archives
rss: /atom.xml
banner: "images/banner.jpg"

# Content
excerpt_link: Read More
fancybox: true
recent_posts_limits: 5

# Sidebar
sidebar: right
widgets:
- tag
- tagcloud
- recent_posts

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.png
twitter:
fb_admins:
fb_app_id:

gitalk:
  on: true
  owner: dukeluo
  repo: slogan
  admin: ['dukeluo']
  clientID: ac13c3b3628335d35671
  clientSecret: 5c2b1d85739f26158c96d18b9eddc1183bf4b010
